name: buildAutomation_1-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm audit fix       # we recommend to use "npm audit" instead of "npm audit fix" because applying fixes automatically can break the build
      - run: npm run grunt clean
      - run: npm run grunt lint
      - run: npm run grunt test
      - run: npm run grunt concat
      - run: npm run grunt correctConcatenatedFile
